dist:
  name: uno-zen
  css: assets/css
  js: assets/js

src:
  sass:
    main: assets/scss/uno-zen.scss
    files: [assets/scss/**/**]

  js:
    common:
      main:
        [
          assets/js/src/__init.coffee,
          assets/js/src/main.coffee,
          assets/js/src/cover.coffee,
        ]
      vendor:
        [
          assets/vendor/instantclick/instantclick.js,
          assets/vendor/pace/pace.min.js,
          assets/vendor/reading-time/build/readingtime.min.js,
        ]
    post: [assets/vendor/fitvids/jquery.fitvids.js, assets/js/src/prism.js]

  css:
    main: assets/css/uno-zen.css
    vendor: assets/css/vendor
# banner = [ "/**"
#            " * <%= pkg.name %> - <%= pkg.description %>"
#            " * @version <%= pkg.version %>"
#            " * @link    <%= pkg.homepage %>"
#            " * @author  <%= pkg.author.name %> (<%= pkg.author.url %>)"
#            " * @license <%= pkg.license %>"
#            " */"
#            "" ].join("\n")
