name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm install -g bower
      - run: bower install
      - run: npm install gulp@4.0.2 --also=dev
      - run: gulp build
      - name: Zip Folder
        run: zip -r uno-zen-revised-${{ env.TAG }}.zip *.hbs *.md *.html package.json partials/ assets/js/uno-zen-revised.common.js assets/js/uno-zen-revised.post.js assets/css/uno-zen-revised.css assets/fonts/ assets/img/
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'uno-zen-revised-${{ env.TAG }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}